import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'fabricio' at '10/24/18 3:38 PM' with Gradle 2.14.1
 *
 * @author fabricio, @date 10/24/18 3:38 PM
 */
public class GmailTest {
	@Test
	public void testSomeLibraryMethod() {

	}
}
